-- Import des données PostgreSQL vers Supabase
-- Généré depuis le dump PostgreSQL

-- Nettoyer les tables existantes
TRUNCATE TABLE hadiths, coran, dhikrs, douaas, savants RESTART IDENTITY CASCADE;

-- ============================================
-- TABLE: coran (5 rows)
-- ============================================
INSERT INTO coran (id, sujet, sourate, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(1, 'Croyance', '''Āli `Imrān / ''āyah 190', 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالأَرْضِ وَاخْتِلاَفِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِأُوْلِي الألْبَابِ ', 'Certes, dans la création des cieux et de la terre et dans le changement du jour et de la nuit, il y a des preuves pour ceux qui sont dotés de raison', 'Inna khalqi fī s-samāwāti wa l-''arḍi wākhtilāfi l-layli wa n-nahāri lāyātin li''oūlī l-''albābi', 'Dans ce verset (''āyah), Dieu nous indique que le monde est une preuve de Son existence ; ainsi selon la raison, les cieux, la terre et les autres créatures auraient pu ne pas exister ou exister à une autre époque, avec une autre forme, ou avec d''autres caractéristiques. L''existence de ces créatures signifie qu''il y a Un Créateur Qui les a spécifiées par le fait d''exister au lieu de ne pas exister, d''exister à cette époque plutôt qu''à une autre, d''avoir ces caractéristiques plutôt que d''autres.', 'croyance'),
(2, 'Croyance ', 'Al-''A`rāf / ''āyah 185', 'أَوَلَمْ يَنظُرُوا في مَلَكُوتِ السَّمـٰواتِ والأرضِ', 'Ne méditent-ils pas au sujet des cieux et de la terre ?', '''awalam yanḍhouroū fī malakoūti s-samāwāti wa l-''arḍ', 'Ce verset (''āyah) blāme le fait de ne pas méditer sur la création', 'croyance'),
(3, 'Croyance ', 'soūrat al-Moulk / ''āyah 10', 'وَقَالُوا لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِي أَصْحَابِ السَّعِيرِ', 'et ils ont dit si nous avions écouté [avec acceptation] ou si nous avions raisonné, nous n''aurions pas fait partie des gens de l''enfer', NULL, 'Ces versets nous indiquent que la raison est une preuve dans la religion. Bien que la base de la religion soit le Qour''ān et le ḥadīth, la raison est un témoin de la religion. Ainsi, rien de ce qui est parvenu dans la religion, ne contredit la raison.', 'croyance'),
(4, 'Croyance ', NULL, 'وَهُوَ مَعَكُمۡ أَيۡنَ مَا كُنتُمۡۚ', 'Cela veut dire qu''Il sait toute chose par Sa science.', 'Wahouwa ma^akoum ''ayna ma kountoum', 'C''est ce qu''ont dit Ath-Thawriyy, Ach-Chafi^iyy, Ahmad, Malik et bien d''autres', 'croyance'),
(5, 'Croyance, taawil', 'Al-Baqarah / 26', 'يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًاۡۚ', 'Allah égare par le Qour''an beaucoup de gens et Il guide par lui beaucoup de gens.', 'Youdillou bihi kathiran wayahdi bihi kathira', 'Ainsi, Allah a voulu de toute éternité que certains soient guidés par le Qour''an et que d''autres soient égarés par leur mauvaise interprétation des versets non explicites du Qour''an', 'croyance, taawil, coran');

SELECT setval('coran_id_seq', (SELECT MAX(id) FROM coran));

-- ============================================
-- TABLE: dhikrs (3 rows)
-- ============================================
INSERT INTO dhikrs (id, sujet, texte_arabe, texte_francais, phonetique, explication, tag, commentaire) VALUES
(1, 'Dhikr', 'لا إله إلا الله محمد رسول الله', 'Il n''y a de dieu qu''Allah et Muhammad est son messager.', 'Lā ilāha illā Allāhou Muhammadou rasoulou Allāh', '', 'croyance, tawhid', 'La base de la croyance islamique.'),
(2, 'Invocation quand on se réveille au milieu de la nuit', 'أَعُوذُ بكلماتِ اللهِ التآماتِ من غضبِهِ وعقابِهِ وشَرِّ عبادِهِ ومِنْ هَمَزَاتِ الشَّيَاطِينِ وأَنْ يَحضُرُونَ', 'Nous enseignons cette dhikr à ceux qui avait atteint le discernement parmi nos enfants. Et ceux qui n''avait pas encore atteint le discernement, on l''écrivait et on l''accrochait à leurs cous', '''a`ôudhou bi kalimâti l-Lâhi t-tâmmâti min ghaḍabihi wa `iqâbih wa charri `ibâdih wa min hamazâti ch-chayâṭîn wa ''an yaḥḍourôun', 'Invocation demandant la paix et la protection.', 'protection', 'At-tirmîdhiyy a dit: « c''est un ḥadīth qui est ḥaçan »'),
(3, 'Dhikr', 'الله الله ربّي لا أُشركُ به شيئًا', 'Allāh, Allāh est mon Seigneur, je ne lui associe rien.', 'Allāhou Allāhou rabbī lā `ouchrikou bihī chay`â', '', 'tahsin, protection', 'Évocation à faire matin et soir.');

SELECT setval('dhikrs_id_seq', (SELECT MAX(id) FROM dhikrs));

-- ============================================
-- TABLE: douaas (5 rows)
-- ============================================
INSERT INTO douaas (id, sujet, texte_arabe, texte_francais, phonetique, explication, tag, commentaire) VALUES
(1, 'Invocation à dire lorsque le vent souffle ', 'اللَّهُمَّ إِنِّي أسْألُكَ خَيْرَهَا وخَيْرَ مَا فِيْهَا وَخَيْرَ مَا أُرْسِلَتْ بِهِ وأعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا فِيْهَا وَشَرِّ مَا أُرْسِلَتْ بِهِِ', 'Ô mon Dieu, je Te demande son bien, le bien qu''il contient et le bien avec lequel il a été envoyé, et je cherche refuge auprès de Toi contre son mal, le mal qu''il contient et le mal avec lequel il a été envoyé.', '', '', 'vent', ''),
(2, 'Voyage', 'اللهُ أكْبَر، اللهُ أكْبَر، اللهُ أكْبَر، اللَّهُمَّ إِنَّا نَسْأَلُكَ في سَفَرِنَا هذا البِرَّ والتَّقوى ومِنَ العَمَلِ ما تَرْضى، اللَّهُمَّ هَوِّنْ علَيْنا سفَرَنَا هذا وَاطْوِ عنَّا بُعْدَهُ، اللَّهُمَّ أَنتَ الصَّاحِبُ في السَّفَرِ وَالخَلِيفَةُ في الأهْلِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وعْثَاءِ السَّفَرِ، وكآبةِ المَنظَرِ، وَسُوءِ المُنْقلَبِ في المالِ والأهلِ', ' Allāh mérite plus de vénération que tout autre. Ô Allāh, nous Te demandons pour notre voyage que voici la bienfaisance et la piété, et nous Te demandons de nous accorder d''accomplir des oeuvres que Tu agrées. Ô Allāh, facilite-nous ce voyage que nous voulons entreprendre et fais que la distance nous soit raccourcie. Ô Allāh, Tu es Celui Qui nous préserve durant ce voyage par Ta grâce et Tu es Celui à Qui nous confions nos familles. Ô Allāh, nous recherchons Ta préservation contre les difficultés du voyage et contre le fait de voir de mauvaises choses durant ce voyage, et contre un mauvais retour aux biens et à la famille', 'Allāhou ''akbar, Allāhou ''akbar, Allāhou ''akbar, Allāhoumma ''inna nas''alouka fi safarinā hādhā l-birra wa t-taqwā, wa mina l-ʿamali ma tarḍā, Allāhoumma hawwin ʿalaynā safaranā hādhā wa ṭwi ʿannā bouʿdah, Allāhoumma ''anta ṣ-ṣāḥibou fi s-safari wa l-khalīfatou fi l-''ahli, Allāhoumma ''innī ''aʿoūdhou bika min waʿthā''i s-safari wa ka''ābati l-manḍhari wa soū''i l-mounqalabi fi l-māli wa l-''ahl', 'ʿAbdou l-Lāh Ibnou ʿOumar, que Allāh l''agrée lui et son père, a rapporté que le Messager de Allāh ṣalla l-Lāhou ʿalayhi wa sallam a enseigné cette invocation pour celui qui part en voyage', 'voyage', NULL),
(3, 'voyage', 'أَسْتَوْدِعُكَ اللهَ الَّذِي لاَ تَضِيعُ وَدَائِعُهُ', 'Je te confie à Allāh, Celui qui préserve ce qui Lui est confié', '''astawdiʿouka l-Lāha l-Ladhī lā taḍīʿou wadā''ʿouh', NULL, 'voyage', 'ḥadīth rapporté par l''Imam ''Aḥmad et autre d''après Aboū Hourayrah'),
(4, 'Voyage', 'أستَودِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ', 'Je confie à Allāh ta religion, ton honnêteté et tes dernières œuvres', '''astawdiʿou l-Lāha dīnaka wa ''amānataka wa khawātīma ʿamalik', NULL, NULL, 'ʿAbdou l-Lāh Ibnou ʿOumar Ibnou l-Khaṭṭāb, que Allāh les agrée, disait lorsque quelqu''un venait le voir avant d''entamer un voyage: « Rapproche-toi de moi afin que je te salue tout comme nous saluait le Messager de Allāh ṣalla l-Lahou ʿalayhi wa sallam, il nous saluait pour un départ en voyage avec cette invocation'),
(5, 'Pardon', 'اللهُمَّ أنْتَ رَبِّي لا إلهَ إلا أنْتَ خَلَقْتَنِي وَأنَا عَبْدُكَ وَأنَا عَلَى عَهْدِكَ وَوَعْدِكَ ما اسْتَطَعْتُ أعُوْذُ بِكَ مِن شَرِّ مَا صَنَعْتُ أبُوْءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأبُوْءُ بِذَنْبِي فَاغْفِرْ لِي فَإنَّهُ لا يَغْفِرُ الذُّنُوبَ إلا أنْتَ', 'Ô Allāh Tu es mon Seigneur. Il n''est de dieu que Toi. Tu m''as créé et je suis Ton esclave, et je suis sur l''engagement que j''ai pris (la foi et l''obéissance à Dieu) autant que je peux. Je recherche Ta préservation contre le mal que j''ai fais. Je reconnais les bienfaits que Tu m''as accordés et je reconnais mes péchés, alors, je te demande de me pardonner. Certes nul autre que Toi ne pardonne les péchés', 'Allāhoumma ''anta rabbī lā ''ilāha ''il-lā ''anta khalaqtanī wa ''anā ʿabdouk wa ''anā ʿalā ʿahdika wa waʿdika mastaṭaʿt ''aʿoūdhou bika min charri mā ṣanaʿt aboū''ou laka bi niʿmatika ʿalayya wa aboū''ou bi dhanbī faghfir lī fa ''innahoū lā yaghfirou dh-dhounoūba ''il-lā ''ant', NULL, 'pardon', 'Al-Boukhāriyy a rapporté dans son ṣaḥīḥ, ainsi que ''Aḥmad dans son Mousnad, d''après Chaddād Ibnou ''Aws, d''après le Prophète ṣalla l-Lāhou ʿalayhi wa sallam, l''invocation suivante appelée sayyidou l-''istighfār - la maîtresse des invocations pour la demande du pardon');

SELECT setval('douaas_id_seq', (SELECT MAX(id) FROM douaas));

-- ============================================
-- TABLE: savants (from parole - 8 rows)
-- ============================================
INSERT INTO savants (id, sujet, savant, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(1, 'La non ressemblance de Allah', 'Abu Hanifah', 'يد الله فوق أيديهم، وليست كأيدي خلقه، ليست بجارحة، وهُو خالق الأيدي. ووجهُه ليس كوُجوه خلقه، وهُو خالق كُلِّ الوُجوه', ' اليد (al-yad) attribué à Dieu n''a aucune ressemblance avec les mains des créatures. Ce n''est pas un membre. Il est le Créateur des mains. الوجه (al-wajh) attribué à Dieu n''a aucune ressemblance avec les visages des créatures. Il est le Créateur de tous les visages.', NULL, 'Un autre argument qui montre que Abou Hanifah ne rejette pas toute interprétation, réside dans sa parole dans Al-Fiqh al-Absaṭ où il dit lorsqu''il parle de l''attribut de Dieu اليد (al-yad)', 'Exemption, croyance, Attributs'),
(2, 'La non ressemblance de Allah', 'Abu Hanifah', 'فمَا ذكره الله تعالَى في القُرآن مِن ذكر الوجه واليد والنَّفس، فهُو له صفة بلا كيف', 'ce que Dieu a cité dans le Qour''an à savoir الوجه, اليد et النَّفس, il s''agit d''attributs de Dieu sans comment', NULL, 'Sa parole "sans comment" est une interprétation qui rejette le sens littéral, il s''agit d''une interprétation globale car il n''a pas précisé le sens voulu.', 'Exemption, croyance, Attributs'),
(3, 'La non ressemblance de Allah', 'Abu Hanifah', 'ويراه المُؤمنون وهُم في الجنَّة بأعيُن رُؤوسهم بلا تشبيه ولا كيفيَّة ولا كمِّيَّة ولا يكون بينه وبين خلقه مسافة', ' Les croyants Le verront de leurs yeux, sans aucune ressemblance avec les créatures, ni comment, ni quantité, et sans qu''il y ait une distance entre Lui et eux.', NULL, 'Et dans Al-Fiqh al-Akbar il ajoute à propos de la vision de Dieu au Paradis', 'Exemption, croyance, Attributs'),
(4, 'La non ressemblance de Allah', 'Al-Matouridiyy', 'بَلْ يَدَاهُ مَبْسُوطَتَانِ', 'Par ailleurs, Al-Matouridiyy — qui était hanafite — a commenté le verset 64 de sourate Al-Mai''dah : En disant qu''il signifie : « Ses bienfaits sont largement répandus » c''est-à-dire que Dieu accorde ses bienfaits à qui Il veut et Il prive qui Il veut.', NULL, 'Et il a ajouté : « Concernant les termes cités comme اليد, القبضة ou اليمين, il s''agit de Lui attribuer la force, la souveraineté et la puissance sur toute chose. » Cette interprétation montre que Al-Matouridiyy a bien compris que Abou Hanifah ne voulait pas exclure systématiquement toute interprétation du terme اليد par le bienfait car il l''a interprété lui-même par ce sens dans le verset de sourate Al-Mai''dah.', 'Exemption, croyance, Attributs'),
(5, 'La non ressemblance de Allah', 'Imam At-Tahawiyy', 'وَمَنْ وَصَفَ اللهَ بِمَعْنًى مِنْ مَعَانِي البَشَرِ فَقَدْ كَفَر', 'Celui qui qualifie Dieu par une des attributs des humains aura mécru » c''est-à-dire qu''il n''est pas musulman.', NULL, NULL, 'Exemption, croyance, Attributs'),
(6, 'La non ressemblance de Allah', 'Imam Ach-Chafi^iyy', 'مَنِ انْتَهَضَ لِمَعرِفةِ مُدَبِّرِهِ فَانتَهَى إِلى مَوجُودٍ يَتَصَوَّرُهُ بِفِكرِهِ فَهُوَ مُشَبِّه ومَنِ انتَهَى إِلى العَدَمِ الصِّرْفِ فهُوَ مُعَطِّل ومَنِ انتَهَى إِلى مَوجُودٍ واعْتَرَفَ بِالعَجْزِ عَنْ إِدْراكِهِ فَهُوَ مُوَحِّد', 'Celui qui tente de connaître son Créateur et qui aboutit à un être qu''il imagine par son esprit, c''est un assimilationniste et Celui qui aboutit à l''inexistence du Créateur c''est un athée. Et celui qui aboutit à l''existence d''un Créateur en reconnaissant qu''il est incapable d''en connaître la réalité, c''est un croyant en l''Unicité de Dieu.', NULL, 'Reprenons phrase par phrase la parole de l''Imam Ach-Chafi^iyy', 'Exemption, croyance, Attributs'),
(7, 'L''interpretation Qour''an', 'Ahmad Ar-Rifa^iyy', 'صونو عقائدكم من التّمسّك بظاهر ما تشابه من الكتاب والسّنّة فإنّ ذالك من أصول الكفر', 'Préservez vos croyances de l''attachement au sens apparent de ce qui n''est pas explicite parmi les expressions du Livre [du Qour''an] et de la Sounnah car c''est une des sources de mécréance.', 'sounou ^aqa''idakoum mina t-tamassouki bi dhahiri ma tachabaha mina l-kitabi was-sounnah ; fa''inna dhalika min ''ouçouli l-koufr', 'Ahmad Ar-Rifa^iyy qui est un spécialiste de l''exégèse du Qour''an a dit dans son livre "Al-bourhanou l-mou''ayyad"', 'croyance, taawil, coran'),
(8, 'La non ressemblance de Allah', 'Imam An-Naçafi', ' ويجوز أن يقال بأن لله تعالى يداً بالعربية ، ولا يجوز بالفارسية ، واليد من صفاته الأزلية بلا كيف ولا تشبيه كالسمع والبصر والعلم والقدرة والحياة والإرادة والكلام. فإن الله تعالى سميع بلا جارحة ، بصير بلا عين ، عالم بلا آلة ، مريد بلا قلب ، متكلم بلا لسان وشفتين ، وكذلك اليد من صفاته الأزلية بلا كيف وتشبيه وجارحة. فنقرُّ باليد والمراد به ما أراد الله تعالى', 'Il est permis de dire que Allâh ta''âlâ a un yad en Arabe, mais ce n''est pas permis en Persan. Et al-yad est l''un de Ses attributs éternels, sans comment (bila kayf) et sans similarité (wa lâ tachbîh) comme l''ouïe, la vue, la science, la puissance, la vie, la volonté, et la parole.', NULL, 'L''Imâm An-Naçafi commence en confirmant l''attribut d''al-yad au sujet de Allâh, mais il précise qu''il n''est pas permis de le traduire [mot à mot] en Persan.', 'Exemption, croyance, Attributs');

SELECT setval('savants_id_seq', (SELECT MAX(id) FROM savants));

-- ============================================
-- TABLE: hadiths (65 rows)
-- Note: Due to size, splitting into multiple INSERT statements
-- ============================================
INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(1, 'Début de la révélation ', 'Al-Boukhāriyy', NULL, 'Sahih', 'قَالَ الشَّيْخُ الْإِمَامُ الْحَافِظُ أَبُو عَبْدِ اللَّهِ مُحَمَّدُ بْنُ إِسْمَاعِيلَ بْنِ إِبْرَاهِيمَ بْنِ الْمُغِيرَةِ الْبُخَارِيُّ رَحِمَهُ اللَّهُ تَعَالَى آمِينَ:
كَيْفَ كَانَ بَدْءُ الوَحْيِ إِلَى رَسُولِ اللَّهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ؟
وَقَوْلُ اللَّهِ جَلَّ ذِكْرُهُ: ﴿إِنَّا أَوْحَيْنَا إِلَيْكَ كَمَا أَوْحَيْنَا إِلَى نُوحٍ وَالنَّبِيِّينَ مِنْ بَعْدِهِ﴾ [النساء: 163].', NULL, NULL, NULL, 'révélation, croyance'),
(2, 'Début de la révélation ', 'Al-Boukhāriyy', '`Aichah', 'Sahih', 'قَالَ: حَدَّثَنَا عَبْدُ اللَّهِ بْنُ يُوسُفَ، قَالَ: أَخْبَرَنَا مَالِكٌ، عَنْ هِشَامِ بْنِ عُرْوَةَ، عَنْ أَبِيهِ، عَنْ عَائِشَةَ أُمِّ المُؤْمِنِينَ رَضِيَ اللَّهُ عَنْهَا، أَنَّ الحَارِثَ بْنَ هِشَامٍ رَضِيَ اللَّهُ عَنْهُ سَأَلَ رَسُولَ اللَّهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ', NULL, NULL, NULL, 'révélation, croyance'),
(3, 'Début de la révélation', 'Al-Boukhāriyy', 'Omar Ibnou Al-Khattab', 'Sahih', ' قَالَ: حَدَّثَنَا الحُمَيْدِيُّ عَبْدُ اللَّهِ بْنُ الزُّبَيْرِ، قَالَ: حَدَّثَنَا سُفْيَانُ، قَالَ: حَدَّثَنَا يَحْيَى بْنُ سَعِيدٍ الأَنْصَارِيُّ، قَالَ: أَخْبَرَنِي مُحَمَّدُ بْنُ إِبْرَاهِيمَ التَّيْمِيُّ', NULL, NULL, NULL, 'intention, actes'),
(4, 'Début de la révélation', 'Al-Boukhāriyy', '`Aichah', 'Sahih', ' قَالَ: حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ، قَالَ: حَدَّثَنَا اللَّيْثُ، عَنْ عُقَيْلٍ، عَنِ ابْنِ شِهَابٍ، عَنْ عُرْوَةَ بْنِ الزُّبَيْرِ، عَنْ عَائِشَةَ أُمِّ المُؤْمِنِينَ', NULL, NULL, NULL, 'révélation, croyance'),
(5, 'Début de la révélation', 'Al-Boukhāriyy', NULL, 'Sahih', 'قَالَ ابْنُ شِهَابٍ: وَأَخْبَرَنِي أَبُو سَلَمَةَ بْنُ عَبْدِ الرَّحْمَنِ، أَنَّ جَابِرَ بْنَ عَبْدِ اللَّهِ الأَنْصَارِيَّ، قَالَ', NULL, NULL, NULL, 'révélation, croyance'),
(6, 'Début de la révélation', 'Al-Boukhāriyy', 'Ibnou l-`abbās', 'Sahih', 'قَالَ: حَدَّثَنَا مُوسَى بْنُ إِسْمَاعِيلَ، قَالَ: حَدَّثَنَا أَبُو عَوَانَةَ، قَالَ: حَدَّثَنَا مُوسَى بْنُ أَبِي عَائِشَةَ', NULL, NULL, NULL, 'révélation, croyance'),
(7, 'Début de la révélation', 'Al-Boukhāriyy', 'Ibnou l-`abbās', 'Sahih', 'قَالَ: حَدَّثَنَا عَبْدَانُ، قَالَ: أَخْبَرَنَا عَبْدُ اللَّهِ قَالَ: أَخْبَرَنَا يُونُسُ، عَنِ الزُّهْرِيِّ', NULL, NULL, NULL, 'révélation, croyance'),
(8, 'Début de la révélation', 'Al-Boukhāriyy', NULL, 'Sahih', 'قَالَ: حَدَّثَنَا أَبُو اليَمَانِ الحَكَمُ بْنُ نَافِعٍ قَالَ: أَخْبَرَنَا شُعَيْبٌ، عَنِ الزُّهْرِيِّ', NULL, NULL, NULL, 'révélation, croyance'),
(9, 'Exemption de Allah', 'Al-Boukhāriyy', NULL, 'Sahih', ' كان الله و لم يكن شىء غيره', NULL, NULL, NULL, 'exemption, croyance'),
(10, 'Exemption de Allah', 'Al-Boukhāriyy', NULL, 'Sahih', 'كَانَ اللهُ وَلَمْ يَكُنْ شَىءٌ غَيْرُهُ ', 'Dieu existe de toute éternité et rien d''autre que Lui n''est de toute éternité', 'Kāna l-Lāhou wa lam yakou, chay''oun ghayrouh', NULL, 'exemption, croyance');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(11, 'Croyance', 'Al-Boukhāriyy', NULL, 'Sahih', ' فَإِنَّ اللهَ حَرَّمَ عَلَى النارِ – أَيِ الدَّوامَ فِيها لِلْأَبَدِ – مَنْ قالَ لَا إِلَهَ إِلَّا اللهُ يَبْتَغِي بِذَلِكَ وَجْهَ اللهِ ', 'Certes Dieu a voulu que ne reste pas éternellement en enfer celui qui aura dit : لا إله إلَّا الله', 'fa''inna l-Laha harrama ^ala n-nar –''ayi d-dawama fiha lil-''abad– man qala la ''ilaha ''il-la l-Lahou yabtaghi bidhalika wajha l-Lah', 'Ce حديث hadith honoré et d''autres indiquent que celui qui dit les deux témoignages en croyant et en acceptant leur signification, et qui meurt sur cela, nécessairement, il entrera au Paradis même s''il est châtié avant cela à cause de ses péchés si Dieu ne lui pardonne pas.', 'enfer, croyance'),
(12, 'Exemption de Allah', 'Al-Boukhāriyy', NULL, 'Sahih', 'يَخْرُجُ مِنَ النّارِ مَنْ قالَ لَا إِلَهَ إِلَّا اللهُ وَفِي قَلْبِهِ وَزْنُ ذَرَّةٍ مِنْ إِيمانٍ', 'Sortira de l''enfer quiconque a dit : لا إله إلَّا الله –Il n''est de dieu que Dieu– en ayant dans son cœur le minimum de la foi.', 'yakhroujou mina n-nar man qala la ''ilaha ''il-la l-lah wafi qalbihi waznou dharratin min ''iman', NULL, 'exemption, croyance'),
(13, 'tawhid', 'Imam Malik', NULL, 'Sahih', 'أَفْضَلُ ما قُلْتُ أَنَا وَالنَّبِيُّونَ مِنْ قَبْلِي لا إِلَهَ إِلَّا اللهُ', ' La meilleure des paroles que j''ai dite, moi ainsi que les prophètes qui m''ont précédé c''est لاَ إِلَهَ إِلَّا الله –Il n''est de dieu que Dieu–.', '''afdalou ma qoultou ''ana wan-nabiyyouna min qabli la ''ilaha ''il-la l-Lah', 'Rapporté dans Al-Mouwatta ', 'parole, croyance, tawhid'),
(14, 'Attributs de Allah', 'Abu Dawoud', NULL, NULL, 'ما شاءَ اللهُ كانَ وما لَمْ يَشَأْ لَمْ يَكُنْ', 'Ce que Dieu veut est, et ce qu''Il ne veut pas n''est pas', 'ma cha''a l-Lahou kana wama lam yacha'' lam yakoun', 'Tout ce qui entre en existence comme bien et comme mal, comme obéissance et comme désobéissance, comme grâce et comme épreuve, tout cela existe par la volonté de Dieu et par Sa prédestination.', 'parole, croyance, attributs'),
(15, 'Mécréance', 'At-Tirmidhiyy', NULL, NULL, 'إِنَّ العَبْدَ لَيَتَكَلَّمُ بِالكَلِمَةِ لاَ يَرَى بِهَا بَأْسًا يَهْوِي بِهَا فِي النّارِ سَبْعِينَ خَرِيفًا', 'Certes, il arrive que quelqu''un dise une parole dans laquelle il ne voit pas de mal, mais à cause de laquelle il chutera en enfer pendant soixante-dix automnes.', '''inna l-^abda layatakallamou bil-kalimati la yara biha ba''sa yahwi biha fi n-nari sab^ina kharifa', 'Le Messager de Dieu a donc indiqué dans ce حديث hadith qu''il est possible que quelqu''un dise une parole qu''il ne voit pas comme étant nuisible pour lui-même, mais qui le fera chuter pendant soixante-dix ans en enfer.', 'mécréance, apostasie, enfer'),
(16, 'Attributs de Allah', 'Al-Bayhaqiyy', NULL, NULL, 'أَنْتَ الظَّاهِرُ فَلَيْسَ فَوْقَكَ شَىْءٌ وَأَنْتَ البَاطِنُ فَلَيْسَ دُونَكَ شَىْءٌ ', 'Tu es الظَّاهِر Adh–Dhahir, rien n''est donc au-dessus de Toi et Tu es البَاطِن Al-Batin, rien n''est donc en dessous de Toi.', '''anta dh–Dhahirou falayça fawqaka chay'' wa''anta l-Batinou falayça dounaka chay''', 'Le Hafidh Al-Bayhaqiyy a dit dans son livre Al-''Asma''ou was–Sifat', 'attributs, exemption'),
(17, 'Croyance', 'Ibnou Hibban', NULL, 'Sahih', 'وَيْلٌ لِمَنْ قَرَأَهَا وَلَمْ يَتَفَكَّرْ فِيها', 'Malheur à celui qui récite ce verset et ne médite pas dessus.', '''anta dh–Dhahirou falayça fawqaka chay'' wa''anta l-Batinou falayça dounaka chay''', 'En effet, il a été rapporté du Messager de Dieu صلَّى الله عليه وسلم qu''il a dit au sujet du verset', 'méditation, croyance'),
(18, 'Tombe', 'At-Tirmidhiyy', NULL, NULL, ' القَبْرُ رَوضةٌ مِن رِياضِ الجنّةِ أو حُفرةٌ مِن حُفَرِ النَّارِ', ' La tombe peut être comme l''un des jardins du Paradis ou comme l''un des antres de l''enfer.', 'al-qabrou rawdatoun min riyadi l-jannati ''aw houfratoun min houfari n-nar', NULL, 'tombe, chatîment'),
(19, 'Tombe', 'At-Tirmidhiyy', NULL, NULL, ' نعم عَذابُ القَبرِ حَقٌّ', 'Oui, le supplice de la tombe est une vérité.', 'na^am ^adhabou l-qabri haqq', 'Et dans les Sounan de An-Naça''iyy d''après ^A''ichah, que Dieu l''agrée', 'tombe, chatîment'),
(20, 'Tombe', 'At-Tirmidhiyy', NULL, NULL, 'أَتُـرَدُّ عَلَيْنَا عُقولُنا يا رسولَ الله ؟  نَعَم كهَيْئَتِكمُ اليَوم', ' Est ce que nous reprendrons conscience, ô Messager de Dieu ? » Le Prophète lui avait répondu : Oui, tout comme vous êtes conscients aujourd''hui.', '''atouraddou ^alayna ^ouqoulouna ya Raçoula l-Lah ? na^am kahay''atikoumou l-yawm', ' c''est ce qui est rapporté de notre maître ^Oumar Ibnou l-Khattab que Dieu l''agrée', 'tombe, chatîment');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(21, 'Tombe', 'At-Tirmidhiyy', NULL, NULL, 'فأَكْثِرُوا مِنْ ذِكْرِ هَاذِمِ اللَّذَّاتِ الْمَوْتِ', ' Rappelez-vous souvent de celle qui détruit les plaisirs, à savoir la mort', NULL, ' c''est ce qui est rapporté de notre maître ^Oumar Ibnou l-Khattab que Dieu l''agrée', 'tombe, chatîment'),
(22, 'Tombe', 'At-Tirmidhiyy', NULL, NULL, '.ارْقُدْ مَنْهُوشًا، فَمَا مِنْ دَابَّةٍ فِى الأَرْضِ إِلَّا ولَها فِى جَسَدِهِ نَصِيبٌ', 'Reste ! Tu seras atterré et mordu. Il n''y aura pas un animal sous terre sans qu''il n''ait une part de son corps', '''ourqoud manhoucha fama min dabbatin fi l-''ardi ''il-la walaha fi jaçadihi nasib', 'Parmi ce qui relève du supplice dans la tombe également', 'tombe, chatîment'),
(23, 'Tombe', 'At–Tabaraniyy', NULL, NULL, ' ويُسَلَّطُ عَلَيْهِ عَقَارِبُ وثَعَابِينُ', 'Il sera assailli par des scorpions et des serpents', 'wayouçallatou ^alayhi ^aqaribou watha^abinou', 'Et dans les Sounan de An-Naça''iyy d''après ^A''ichah, que Dieu l''agrée', 'tombe, chatîment'),
(24, 'Tombe', 'Abou Dawoud', 'Al-Bara'' Ibnou ^Azib', NULL, ' استَعِيذوا باللهِ مِن عَذابِ القَبر، استَعِيذوا باللهِ مِن عَذابِ القَبر ', 'Demandez à Dieu la préservation du supplice de la tombe !', '''ista^idhou bil-Lah min ^adhabi l-qabr, ''ista^idhou bil-Lah min ^adhabi l-qabr', 'Abou Dawoud a rapporté dans ses Sounan d''après Al-Bara'' Ibnou ^Azib', 'tombe, chatîment'),
(25, 'Science', 'Al-Bayhaqiyy', 'hafidh Al-Mizziyy', 'haçan', ' طَلَبُ العِلْمِ فَرِيضَةٌ على كُلِّ مُسْلِم', 'Quérir la science de la religion est une obligation pour tout musulman', '''talabou l-^ilmi faridatoun ^ala koulli mouslim', 'c''est-à-dire « pour tout musulman et toute musulmane ».', 'science, apprentissage'),
(26, 'Science', 'Al-Boukhariyy', NULL, 'Sahih', '  مَنْ يُرِد اللهُ به خَيْرًا يُفَقِّهْهُ في الدِّينِ إِنمَّا العِلْمُ بالتَّعَلُّمِ والْفِقْهُ بالتَّفَقُّهِ', ' Celui pour qui Allāh veut le bien, Il lui facilite l''apprentissage de la religion', 'man youridi l-Lahou bihi khayra youfaqqih-hou fi d-din,, ''inamma l-`ilmou bi t-ta`alloumi wa l-fiqhou bi t-tafaqqouhi', NULL, 'science, apprentissage'),
(27, 'Science', 'Abôu dharr', NULL, 'Sahih', 'إنَّ حُضور مجلس علم أفضل من صلاة ألف ركعة ', 'Assister à une assemblée de science de la religion est mieux que d''accomplir mille rak`ah des prières surérogatoires', '''inna ḥouḍôura majlisi `ilmin ''afḍalou min ṣalâti ''alfi rak`ah', NULL, 'science, apprentissage'),
(28, 'Science', 'Al-Boukhâriyy', NULL, 'Sahih', 'بَلِّغوا عَنِّي وَلَوْ ءَايَةً', 'Transmettez de moi ne serait-ce qu''une ''âyah', NULL, NULL, 'science, apprentissage'),
(29, 'Science', 'at-tirmîdhiyy', NULL, 'Sahih', 'لا يشبعُ مؤمنٌ مِنْ خيرٍ حتى يكونَ مُنتهاهُ الجنّة', 'le croyant ne se rassasie pas d''un bien jusqu''à ce que sa fin soit le paradis', NULL, NULL, 'science, apprentissage'),
(30, 'Science', 'at-tirmîdhiyy', NULL, 'Sahih', 'روى الترمذي وغيره "أن رسول الله صلى الله عليه وسلم دخل المسجد', NULL, NULL, 'Le Prophète صلى الله عليه وسلّم nous a appris que l''intention à elle seule n''est pas suffisante.', 'science, apprentissage, intention');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(31, 'Science', 'ibnou Ḥibbân', NULL, 'Sahih', 'رُبَّ قائم ليس له من قيامه إلا السهر', 'Il se peut que quelqu''un pense faire des prières surérogatoires de nuit et il ne gagne de cela que la veille', NULL, 'C''est à dire que cette personne a fait des actes qui n''étaient pas valables', 'science, apprentissage'),
(32, 'Science', 'Al-Bayhaqiyy', NULL, 'Sahih', 'طَلَبُ العِلْمِ فَرِيضَةٌ عَلى كُلِّ مُسْلِمٍ', 'Rechercher la science est une obligation pour tout musulman', 'talabou l-`ilmi farîḍatoun `alâ koulli mouslim', 'c''est-à-dire que demander la science de la religion est une obligation pour tout musulman responsable.', 'science, apprentissage'),
(33, 'Science', 'Abôu dharr', NULL, 'Sahih', 'لَأَنْ يَتَعَلَّمَ أَحَدُكُمْ بَابًا مِنَ العِلْمِ أَو يُعَلِّمَهُ خَيْرٌ لَهُ مِنْ صَلاةِ ألْفِ رَكْعَةٍ', 'Que l''un de vous apprenne un chapitre de la religion ou l''enseigne aura plus de récompenses', 'la''an yata`allama ''aḥadoukoum bâban min l-`ilmi ''aw you`allimahou khayroun lahou min ṣalâti ''alfi rak`ah', NULL, 'science, apprentissage'),
(34, 'Science', 'Ibnou Mâjah', NULL, 'Haçan', 'يَا أبا ذَر لأن تَغدُوَ فَتَتَعَلَّمَ ءايَة مِن كِتَاب الله خَيْرٌ لَكَ مِن أَن تُصَلّيَ مِائةَ رَكْعَةٍ', ' Ô Abôu Dhar si tu te déplaces et tu apprends une ''Ayah du Qour''ân tu seras plus récompensé', 'man youridi l-Lahou bihi khayra youfaqqih-hou fi d-din', NULL, 'science, apprentissage'),
(35, 'Comportement', 'At- Tirmidhiyy', NULL, 'Sahih', 'إِنَّ الدَّالَ عَلَى الخَيْرِ كَفَاعِلِهِ', 'Celui qui indique le bien aux autres est comme celui qui le fait. ', '''inna d-dala ^ala l-khayri kafa^ilih', 'C''est-à-dire qu''il aura une récompense semblable à la récompense de celui qui le fait', 'comportement, apprentissage'),
(36, 'Purification, Ablutions', 'Abou Hourayrah', 'An-Naça''iyy', 'Sahih', ' إِذَا تَوَضَّأْتُمْ فَابْدَءُوا بِمَيَامِنِكُمْ', 'Quand vous faites le woudou'', commencez par le côté droit. ', '''idha tawadda''toum fabda''ou bimayaminikoum', NULL, 'purification, ablutions'),
(37, 'Purification, Ablutions', '^Oumar', NULL, NULL, ' مَنْ تَوَضَّأَ فَأَحْسَنَ الوُضُوءَ ثُمَّ قَالَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللهُ', NULL, NULL, 'Celui qui fait son woudou'' tout en s''appliquant à le faire parfaitement', 'purification, ablutions'),
(38, 'Purification, Ablutions', NULL, NULL, NULL, ' مَنْ تَوَضَّأَ كَمَا أُمِرَ وَصَّلى كَمَا أُمِرَ غَفَرَ اللهُ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ ', 'Celui qui fait le woudou'' comme il en a reçu l''ordre et qui fait la prière comme il en a reçu l''ordre, Dieu lui pardonnera ses péchés antérieurs.', 'man tawadda''a kama ''oumira wa salla kama ''oumira ghafara l-Lahou lahou ma taqaddama min dhanbih', 'Il s''agit ici des petits péchés', 'purification, ablutions'),
(40, 'Repentir', NULL, NULL, NULL, 'التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لاَ ذَنْبَ لَهُ', 'Celui qui se repent d''un péché, c''est comme s''il ne l''avait pas commis', 'at-tā''ibou mina l-ladhinbi kaman lā dhanbha lah', NULL, 'repentir'),
(41, 'Oeuvres', 'Al-Boukhāriyy', NULL, NULL, ' أَفْضَلُ الأَعْمَالِ إِيمانٌ بِاللهِ ورَسُولِهِ', ' La meilleure des œuvres est la croyance en Allāh et en Son Messager', '''afḍalou l-''a`māli ''īmānoun bi l-Lāhi wa raçoūlih', 'Il s''agit ici des petits péchés', 'oeuvres');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(42, 'Foi', NULL, NULL, NULL, 'وَأَمَّا الْكَافِرُ فَيُطْعَمُ بِحَسَنَاتِهِ في الدُّنْيَا حَتّى إِذا أَفْضَى إِلى الآخِرَةِ لَم يَكُنْ لَهُ مِنْهَا نَصِيبٌ', ' Quant au non-croyant il sera rétribué pour ses bonnes œuvres dans cette vie', 'wa ''amma l-kāfirou fayouṭ`amou biḥasanātihi fi d-dounyā', 'Il s''agit ici des petits péchés', 'foi, croyance'),
(43, 'Foi', 'Mouslim', NULL, 'Sahih', 'أَنْ تُؤْمِنَ باللهِ وَمَلائِكَتِهِ وَكُتِبِهِ ورُسُلِهِ والْيَوْمِ الآخِرِ وتُؤْمِنَ بالْقَدَرِ خَيْرِهِ وَشَرِّهِ', '  La foi est que tu crois en Allāh, en Ses Anges, en Ses Livres, en Ses Prophètes, en Le Jour Dernier', '''an tou''mina bi l-Lāhi wa malā''ikatihi wa koutoubihi wa rouçoulihi wa l-yawmi l-''ākhiri', 'La croyance est telle que l''a expliqué le Prophète Mouḥammad', 'foi, croyance'),
(44, 'Prophètes', 'Al-Boukhāriyy', NULL, 'Sahih', 'الأَنْبِيَاءُ إِخْوَةٌ لِعَلاّتٍ دِينُهُم وَاحِد وَأُمَّهَاتُهُم شَتَّى', 'Les Prophètes sont comme des frères du même père, leur religion est la même et leurs lois diffèrent', 'Al ''anbiyā''ou ''ikhwatoun li`allāt dīnouhoum wāḥid wa ''oummahātouhoum chattā', 'Le prophète Mouḥammad a assimilé les prophètes à des frères du même père du fait que leur religion est la même', 'foi, croyance, prophètes'),
(45, 'Prophètes', NULL, NULL, NULL, ' أَفْضَلُ مَا قُلْتُ أَنَا وَالنَّبِيُّونَ مِنْ قَبْلِي لاَ إِلَهَ إِلاَّ الله وَحْدَهُ لاَ شَرِيكَ لَهُ ', 'La meilleure des choses que j''ai dite ainsi que les Prophètes qui m''ont précédé', '''Afḍalou mā qoultou ''anā wa n-nabiyyoūna min qablī lā ''ilāha illa l-Lāhou waḥdahou lā charīka lah', NULL, 'foi, croyance, prophètes, paroles'),
(46, 'Comportement', 'Mouslim', NULL, 'Sahih', ' مَن رَّأَى مِنْكُم مُّنكَراً فَلْيُغَيِّرْهُ بِيَدِهِ فإن لم يستطع فبلسانه فإن لم يستطع فبقلبه وذلك أضعف الإيمان', 'Celui d''entre vous qui a su qu''un mal se pratique, qu''il le change par sa main', 'man-ra''â minkoum mounkaran falyoughayyirhou biyadih fa''in lam yastaṭi` fabilisânihi', 'Ce qui est visé par (ra''ā) dans le ḥadīth c''est le fait de prendre connaissance de cette chose blâmable', 'foi, comportement'),
(47, 'Pêchés', ' At-Tirmîdhiyy', NULL, 'Sahih', 'لَا طَاعَةَ لِمَخْلُوقٍ فِي مَعْصِيَةِ الْخَالِقِ ', 'on n''obéit pas à une créature pour désobéir au Créateur ', NULL, 'Il convient au musulman de faire preuve de bon comportement, de patience et d''indulgence envers les musulmans et non musulmans', 'pêchés, obeissance'),
(48, 'Pêchés', 'Al-Boukhâriyy', NULL, 'Sahih', 'مَثَلُ القائمِ في حدود الله', ' L''exemple de celui qui ordonne le bien et interdit le mal', NULL, 'Nous tirons de ce ḥadīth une moralité très importante', 'pêchés, obeissance'),
(49, 'Croyance', 'At- Tirmidhiyy', NULL, 'Haçan', 'إِنَّ العَبْدَ لَيَتَكَلَّمُ بِالكَلِمَةِ لا يَرىَ بِهَا بَأْساً يَهْوِي بِهَا فِي النَّارِ سَبْعِينَ خَرِيفاً ', 'Certes, il arrive que quelqu''un dise une parole dans laquelle il ne voit pas de mal', '''inna l-^abda layatakallamou bi l-kalimati la yara biha ba''san yahwi biha fi n-nari sab^ina kharifa', 'C''est-à-dire une distance parcourue en soixante-dix ans de chute pour atteindre le fond de l''enfer', 'mécréance, apostasie, enfer'),
(50, 'Meilleur parole', 'Imam Malik dans Al-Mouwata', NULL, 'Sahih', 'أَفْضَلُ مَا قُلْتُ أَنَا وَالنَّبِيُّونَ مِنْ قَبْلِي لا إِلهَ إِلَّا اللَّهُْ', 'La meilleure des paroles que j''ai dite, moi ainsi que les prophètes avant moi c''est لا إِلَهَ إِلَّا اللَّهُ', NULL, NULL, 'révélation, croyance, parole');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(51, 'Meilleur des oeuvres', 'Al-Boukhariyy', NULL, 'Sahih', ' إِيمَانٌ بِاللَّهِ وَرَسُولِهُِْ', 'La foi en Dieu et en Son messager.', NULL, 'A propos de la croyance en Dieu et en son messager citons le حديث hadith suivant', 'oeuvres, croyance, parole'),
(52, 'Mawlid', 'Ahmad et par Al-Bayhaqiyy dans Ad-Dala''il', NULL, 'Sahih', 'ذاكَ يَوْمٌ وُلِدْتُ فِيهِ وأُنْزِلَ عَلَيَّ فِيهُِِْ', 'C''est un jour dans lequel je suis né et dans lequel la révélation a commencé à descendre sur moi.', 'dhaka yawmoun woulidtou fihi wa''ounzila ^alayya fih', 'C''est la réponse de notre bien aimé prophète lorsqu''il a été interrogé sur son jeûne les lundis', 'mawlid, innovation'),
(53, 'Bonne croyance', 'At–Tabaraniyy', NULL, 'Sahih', ' الْمُتَمَسِّكُ بِسُنَّتِي – أَيْ شَرِيعَتِي مِنَ العَقِيدَةِ والأَحْكامِ – عِنْدَ فَسادِ أُمَّتِي لَهُ أَجْرُ شَهِيدٍُِِْ', 'Celui qui s''attachera à ma voie – c''est-à-dire à ma chari^ah, à ce qu''elle comporte comme croyances et comme jugements pratiques', 'al-moutamassikou bi-sounnati ^inda façadi ''oummati lahou ''ajrou chahid', NULL, 'bonne croyance'),
(54, 'croyance, ta''wil, Qour''an', 'At–Tabaraniyy', NULL, 'Sahih', 'الْقُرْءانُ حُجَّةٌ لكَ أَوْ عَلَيكَ', 'Le Qour''an est soit une preuve en ta faveur, soit une preuve contre toi', 'Al-Qour''anou houjjatoun laka ''aw ^alayka', 'Ainsi, celui qui donne une mauvaise interprétation des versets du Qour''an, cela se retournera contre lui.', 'croyance, taawil, coran'),
(56, 'Mécréance', 'Al Bayhaqiyy', 'd''après Rāfiʿ ibnou Khadīj le compagnon du Prophète', NULL, 'سيكون في أمتي أقوامٌ يكفرون بالله وبالقرءان وهم لا يشعرون', 'Il y aura des gens de ma communauté qui vont devenir non-croyants en Allāh et en le Qour''ān', 'sayakoūnoun fī ''oumatī ''aqwāmoun yakfouroūna bi l-Lāhi wa bi l-qour''ān wa houm lā yachrouʿoūn', NULL, 'mécréance'),
(57, 'Croyance', 'Mouslim', NULL, 'Sahih', ' الإِيمَانُ أَنْ تُؤْمِنَ بِاللهِ وَمَلاَئِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ وَالْيَوْمِ الآخِرِ وَتُؤْمِنَ بِالْقَدَرِ خَيْرِهِ وَشَرِّهِ', ' La foi est que tu croies en Allāh, en Ses anges, en Ses livres, en Ses messagers et en le jour dernier', NULL, 'La signification de ce ḥadīth est la suivante', 'croyance, prédestination'),
(58, 'Croyance', 'Aboū Dāwoūd', NULL, NULL, 'ما شاء الله كان و ما لم يشأ لم يكن', 'Ce que Dieu veut est, ce qu''Il ne veut pas n''est pas', 'mā chā Allāhou kān wa mā lam yacha'' lam yakoun', 'croyance, prédestination', NULL),
(59, 'Prédestination', 'Mouslim', NULL, 'Sahih', ' إنَّ النّذرَ لا يَرُدُّ منْ قدَرِ اللهِ وإِنّمَا يُستَخْرَجُ بِهِ مِنَ البَخيلِ', 'Le vœu n''empêche pas la destinée de Allāh, seulement c''est par le vœu que l''avare donne', 'inna n-nadhra lā yarouddou min qadari l-Lāh wa ''innamā youstakhrajou bihi mina l-bakhīl', 'La chose dont Allāh sait et veut l''existence de toute éternité, il est indispensable qu''elle soit', 'croyance, prédestination'),
(60, 'Prédestination', 'Ḥāfiḍh ʿAbdou r-Raḥmān Ibnou Abī Ḥātim', 'Aboū Hourayrah', NULL, 'سألت ربي أربعًا فأعطاني ثلاثًا ومنعني واحدة', 'J''ai demandé à Mon Seigneur quatre choses, Il m''en a accordées trois et ne m''en a pas exaucé une.', 'sa''altou rabbi ''arbaʿan fa''aʿṭānī thalāthan wa manaʿanī wāḥidah', 'Mouslim a rapporté ce ḥadīth d''après Thawbān', 'prédestination');

INSERT INTO hadiths (id, sujet, rapporteur, narrateur, statut, texte_arabe, texte_francais, phonetique, explication, tag) VALUES
(61, 'Prédestination', 'Mouslim', 'Aboū Dharr', 'Sahih', ' فَمَنْ وَجَدَ خَيْرًا فَلْيَحْمَدِ اللهَ وَمَنْ وَجَدَ غَيْرَ ذَلِكَ فَلاَ يَلُومَنَّ إِلا نَفْسَهُ', 'Celui donc qui fait des actes de bien, qu''il loue Allāh et celui qui fait contraire à cela, qu''il ne s''en prenne qu''à lui-même', 'faman wajada khayran fa-l-yaḥmadi l-Lāha ; wa man wajada ghayra dhālika falā yaloūmanna ''il-lā nafsah', 'Quand au premier cas, c''est celui qui fait du bien, parce que Allāh taʿālā lui fait la grâce de faire exister ce bien', 'prédestination'),
(62, 'Prédestination', 'At–Tabaraniyy', NULL, NULL, 'إِذَا ذُكِرَ الْقَدَرُ فَأَمْسِكُوا', 'Ne vous plongez pas dans la recherche et la discussion au sujet de la destinée pour tenter d''en percer le secret', '''idhā dhoukira l-qadarou fa''amsikoū', ' En effet, ce qui a précédé ici est une exégèse pour la destinée que les textes ont rapportée.', 'prédestination'),
(63, 'sectes', 'Al-Boukhāriyy', NULL, NULL, 'الْقَدَرِيَّةُ مَجُوسُ هَذِهِ الأُمَّةِ', 'les qadariyyah sont les mazdéens de cette communauté', 'al-qadariyyatou majoūçou hādhihi l-''oummah', 'Saches aussi que le Messager de Allāh a blâmé les qadariyyah qui se divisent en plusieurs groupes.', 'sectes'),
(64, 'Croyance', 'Aboū Dāwoūd', NULL, NULL, 'رُفِعَ الْقَلَمُ عَنْ ثَلاَثَةٍ عَن النَّائِمِ حَتَّى يَسْتَيْقِظَ وعَن الصَّبِيِّ حتَّى يّحْتَلِمَ وعَن المَجْنُونِ حَتَّى يَعْقِل', 'La responsabilité est levée pour trois personnes : celui qui dort jusqu''à ce qu''il se réveille, l''enfant jusqu''à ce qu''il devienne pubère et le fou jusqu''à ce qu''il recouvre la raison', 'roufiʿa l-qalamou ʿan thalâthatin', 'Remarque : Le Messager de Allāh ṣalla l-Lâhou ʿalayhi wa sallam appelait à l''Islam les arabes idolâtres', 'croyance'),
(65, 'Croyance', 'Al-Boukhāriyy', NULL, 'Sahih', 'بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ الله وَ أَنَّ مُحَمَّدًا رَسُولُ اللهِ', 'L''Islam est fondé sur 5 principaux devoirs : le témoignage qu''il n''est de dieu que Dieu et que Mouḥammad est le Messager de Dieu', NULL, 'La maison sacrée est la Kaʿbah qui se trouve à la Mecque', 'croyance');

SELECT setval('hadiths_id_seq', (SELECT MAX(id) FROM hadiths));

-- Vérification finale
SELECT 'coran' as table_name, COUNT(*) as count FROM coran
UNION ALL SELECT 'dhikrs', COUNT(*) FROM dhikrs
UNION ALL SELECT 'douaas', COUNT(*) FROM douaas
UNION ALL SELECT 'savants', COUNT(*) FROM savants
UNION ALL SELECT 'hadiths', COUNT(*) FROM hadiths;
